# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d5ae06282532ff8daff81265f8fdf57dd0f9133277abb6c5c978493d62976ec0278cc0bdaf5fa4b5d36c2b99c521093e882d2af945249db989d584f61d7461
  instagram_client_id: a144e0f50e4b43b4ac8c54292ed81204
  instagram_client_secret: eab7df0e6d75408781ab0e75546b7332
  aws_bucket_name: instabuddies-development

test:
  secret_key_base: 50267c9cc748d08b11b98b5d9dc0532012037bb19857d46fc072997d9565fb70caa6152a2b7fc373bfaf1e6e4461835db4dadc3255bf9692dc09cfaf1ab8261f
  instagram_client_id: a144e0f50e4b43b4ac8c54292ed81204
  instagram_client_secret: eab7df0e6d75408781ab0e75546b7332
  aws_bucket_name: instabuddies-development

production:
  instagram_client_id: <%= ENV['INSTA_ID'] %>
  instagram_client_secret: <%= ENV['INSTA_SECRET'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_bucket_name: instabuddies-production
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
